// <auto-generated />
using System;
using BudgetAppV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetAppV2.Migrations
{
    [DbContext(typeof(BudgetAppContext))]
    [Migration("20260424010555_CategoryBudgets")]
    partial class CategoryBudgets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BudgetAppV2.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BudgetAppV2.Models.CategoryBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Limit")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodBudgetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeriodBudgetId");

                    b.HasIndex("CategoryId", "PeriodBudgetId")
                        .IsUnique();

                    b.ToTable("CategoryBudgets");
                });

            modelBuilder.Entity("BudgetAppV2.Models.PeriodBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalLimit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PeriodBudgets");
                });

            modelBuilder.Entity("BudgetAppV2.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetAppV2.Models.CategoryBudget", b =>
                {
                    b.HasOne("BudgetAppV2.Models.Category", "Category")
                        .WithMany("CategoryBudgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetAppV2.Models.PeriodBudget", "PeriodBudget")
                        .WithMany("CategoryBudgets")
                        .HasForeignKey("PeriodBudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("PeriodBudget");
                });

            modelBuilder.Entity("BudgetAppV2.Models.Transaction", b =>
                {
                    b.HasOne("BudgetAppV2.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetAppV2.Models.Category", b =>
                {
                    b.Navigation("CategoryBudgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetAppV2.Models.PeriodBudget", b =>
                {
                    b.Navigation("CategoryBudgets");
                });
#pragma warning restore 612, 618
        }
    }
}
